language: scala
sudo: false
matrix:
  include:
  - jdk: oraclejdk8
  - jdk: openjdk11
    dist: xenial
script:
- sbt "scalafmtCheck" "test:scalafmtCheck" "scalafmtSbtCheck" "+ compile" "+ test" testAll
cache:
  directories:
  - $HOME/.ivy2/cache
  - $HOME/.sbt/launchers
before_cache:
- find $HOME/.ivy2/cache -name "ivydata-*.properties" | xargs rm
- find $HOME/.ivy2/cache -name "*SNAPSHOT*" | xargs rm -rf
