name: CI
on:
  pull_request:
  push:
    branches:
      - master
jobs:
  test:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        java: [17, 25]
        os: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v7
    - uses: actions/setup-java@v5
      with:
        java-version: ${{matrix.java}}
        distribution: temurin
    - uses: coursier/cache-action@v8
    - uses: sbt/setup-sbt@v1
    - run: sbt
           -v
           --server
           scalafmtCheckAll
           scalafmtSbtCheck
           Test/compile
           testFull
           testAll
    - shell: bash
      run: rm -rf "$HOME/.ivy2/local" || true
           rm -rf "$HOME/.m2" || true
